### ISSUE TITLE
doesnt work with resolve 18?

### ISSUE THREAD

**Issue by rothvideos** [kotylo/davinci-resolve-retime-speed#4]
i need this script in my life, but it always failes now on resolve 18, any chance to fix it? this was a huge time saver for me.
i always get the error message Menu has not been opened. Clip is either too narrow or not fully visible. Move it fully inside the view or zoom a bit

**Comment by kotylo** [comment]
i'll take a look

**Comment by kotylo** [comment]
i'll install v18 today and take a look at it, unfortunately didn't have a chance to use Resolve in a long time yet.

**Comment by kotylo** [comment]
works for me in v18.1 build 16. Hmm, I had seen similar issue as you did on v16 on other machine, but couldn't find a reason for it. Maybe there is something else wrong.

**Comment by rothvideos** [comment]
thanks a lot for checking it out, i will try and troubleshoot and see why it happens for me.

**Comment by rothvideos** [comment]
issue fixed, i replaced the retime curve png with one that i took myself and it worked.  probably different color/font or something like that.  now im gonna try and make a script from this one to change speed of clip to 25% and 50%, also creating speed points. this helped a lot
